name: Build

on:
  - workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug -PabiFilters=arm64-v8a

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mpvkt
          path: app/build/outputs/apk/*/*.apk
